### ISSUE TITLE
I think it is best to give an example.

### ISSUE THREAD

**Issue by taroyutao** [aliyun/alibabacloud-viapi-sdk#21]
`
require __DIR__ . '/vendor/autoload.php';
use AlibabaCloud\SDK\ViapiUtils\ViapiUtils;

// 你的 access_key_id
$accessKeyId = 'LTAIOZZgYX******';
// 你的 access_key_secret
$accessKeySecret = 'v7CjUJCMk7j9aKduMAQLjy********';
// 要上传的文件路径，url 或 filePath
$fileUrl = "c:\Users\Administrator\Desktop\predict.jpg";
// 上传成功后，返回上传后的文件地址

$path = $fileUrl;
$res  = Viapiutils::upload($accessKeyId,$accessKeySecret,$path);

echo $res;

`

**Comment by taroyutao** [comment]
<?php
require __DIR__ . '/vendor/autoload.php';
use AlibabaCloud\SDK\ViapiUtils\ViapiUtils;

// 你的 access_key_id
$accessKeyId = 'LTAIOZZg********';
// 你的 access_key_secret
$accessKeySecret = 'v7CjUJCMk7j9aKduMAQLjy********';
// 要上传的文件路径，url 或 filePath
$fileUrl = "c:\Users\Administrator\Desktop\predict.jpg";
// 上传成功后，返回上传后的文件地址

$path = $fileUrl;
$res  = Viapiutils::upload($accessKeyId,$accessKeySecret,$path);

echo $res;

**Comment by AxiosLeo** [comment]
Updated documentation for usage #31
