### ISSUE TITLE
guzzlehttp/guzzle 版本依赖问题

### ISSUE THREAD

**Issue by sunjim** [aliyun/alibabacloud-viapi-sdk#30]
你好，当我按照咱们文档安装`composer require alibabacloud/viapi-utils` 时提示我版本依赖问题，能否解除这个限制？
![image](https://user-images.githubusercontent.com/5642983/94399509-1131cd80-019a-11eb-9fd6-2433633cfb13.png)

**Comment by AxiosLeo** [comment]
被 composer.lock 锁版本了。
删除项目目录下的 composer.lock 后再执行 `composer require alibabacloud/viapi-utils`

**Comment by AxiosLeo** [comment]
另外，为何在你的项目里会安装 guzzle 6.5.x-dev ?
这个是开发版本，不在 guzzle:^6.3|^7.0 这个范围里。
